language: node_js
node_js:
  - '10'
  - '12'
  - '14'
script:
  - 'npm run lint'
  - 'npm test'
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
